name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  basic:
    strategy:
      matrix:
        # Run tests of ovn-fake-multinode built on multiple supported base
        # images.
        image:
          # The default behavior without setting "url" and "base" variables
          # is expected to work and will use "fedora:latest" as a base image.
          - url: ""
            base: ""
          # Latest Ubuntu base image
          - url: ubuntu:rolling
            base: ubuntu
    env:
      RUNC_CMD: podman
      OVN_SRC_PATH: ovn_git
      OVS_SRC_PATH: ovn_git/ovs
      # https://github.com/actions/runner-images/issues/6282
      XDG_RUNTIME_DIR: ''
      OS_IMAGE: ${{ matrix.image.url }}
      OS_BASE: ${{ matrix.image.base }}
      CENTRAL_IC_ID: ovn-central-az1
    runs-on: ubuntu-latest
    steps:
      - name: Download ovn-fake-multinode
        uses: actions/checkout@v3
      - name: Download OVN main
        uses: actions/checkout@v3
        with:
          repository: ovn-org/ovn
          path: ovn_git
          fetch-depth: 1
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install podman openvswitch-switch
      - name: Build images
        run: sudo -E ./ovn_cluster.sh build
      - name: Start basic cluster
        run: sudo -E ./ovn_cluster.sh start
      - name: Run basic test script
        run: sudo ./.ci/test_basic.sh
      - name: Stop cluster
        run: sudo -E ./ovn_cluster.sh stop
